### ISSUE TITLE
Installtion: undocumented dependencies on 'decouple' and 'django_heroku'

### ISSUE THREAD

**Issue by jbrucker** [NokKbl/khubkhao-recommender#35]
When I tried to install your app according to installation instructions I got this error:

ImportError: No module named 'decouple'

Looks like you are using decouple.config( ) to get some environment variable.

If you are going to use decouple, you could save users a lot of editing of 
settings.py by providing separate .env files for local configuration and Heroku
configuration.  You aren't using config() fluently for the database URL.
See example on https://henriquebastos.net/python-decouple-2-2-strict-separation-of-settings-from-code/

**Comment by jbrucker** [comment]
There is also a dependency on django_heroku in settings.py.

**Comment by NokKbl** [comment]
Sorry for that. I will improve and document them in the installation instructions and add default values to fix [issues #36](https://github.com/NokKbl/khubkhao-recommender/issues/36) also.

Thank you so much for your comment.
