### ISSUE TITLE
Pictures didn’t show up in homepage

### ISSUE THREAD

**Issue by narisasingngam** [NokKbl/khubkhao-recommender#40]

**Comment by New-az** [comment]
Did you '''python mange.py loaddata seed.json''' before run server?

**Comment by NokKbl** [comment]
@narisasingngam You need to open our webpage in Chrome browser. Do the picture show up?

**Comment by narisasingngam** [comment]
It's work!! thank you

**Comment by NokKbl** [comment]
@narisasingngam Great!! Thanks for testing 👍 .
