### ISSUE TITLE
Votings

### ISSUE THREAD

**Issue by bankkeez** [NokKbl/khubkhao-recommender#57]
Vote one rating for many menus and the rate point should decrease but it increase instead.

**Comment by NokKbl** [comment]
It's not a bug but that's what it should be because we separate rate from user's vote and initial rate then compute those value in ratio 80:20, so, if you vote even only one it will increase the rate in the 20 percent part.

**Comment by Driveiei** [comment]
@bankkeez For example, rate in database is 80 but no one vote this menu. 
The formula to compute is 80*0.8 + 0*0.2 = 64/100
If you voted 1 which means 20 points, It will be 80*0.8 +20*0.2 = 68/100 points. 
Ps. if many people vote food, it will compute by mean in 20% part of user.
