### ISSUE TITLE
Why top 25 menus not all menus.

### ISSUE THREAD

**Issue by cynic4018** [NokKbl/khubkhao-recommender#59]
At first, when I logged in to homepage, it shows all menus.
After vote menu, it back to home page with top 25 menus. Should it be all menus?

**Comment by Driveiei** [comment]
That's what we want it to be. Try to imagine if you're voting 1 food and need to wait for loading all pictures every time. So, we want our product to show best 25 foods recommended after you voted to show **recommend food** not all food
