### ISSUE TITLE
Redirecting

### ISSUE THREAD

**Issue by kimvcp** [NokKbl/khubkhao-recommender#60]
After logged in, it should not be able to redirect user to login page by typing the url
(https://khubkhao-rec.herokuapp.com/login/)

Instead of using your logout button, users can use their back button to logout.
You can close this issue, if this is part of your design.

**Comment by NokKbl** [comment]
@kimvcp Thank you for finding our wrong redirect. I will fix it in a minute.

**Comment by NokKbl** [comment]
Fixed.
