### ISSUE TITLE
After I voted specified menu(like Chinese food + noodles dish), page is go back to top 25 recommend menus. 

### ISSUE THREAD

**Issue by KameriiJ** [NokKbl/khubkhao-recommender#61]
After I voted specified menu(like Chinese food + noodles dish), page is go back to top 25 recommend menus. I want to vote another Chinese noodles, but I have to select food ethnic again.

**Comment by NokKbl** [comment]
@KameriiJ Thank you so much for the comment, we will improve this feature next time. 👍
